### ISSUE TITLE
RGB firmware release

### ISSUE THREAD

**Issue by mizma** [mizma/ergoSHIFT#15]
need to test the patched release with RGB support.

https://github.com/mizma/GP2040-CE/releases/tag/v0.7.10-PATCH (updated with the upstream hot-fix 0.7.10 version)

Hi, @jamesjpenguin if you are still interested, I just built the latest firmware with the RGB LED settings configured into the firmware (also with OLED layout support for ergoShift layout).

I have the firmware as pre-release.  Since I don't have the RGB version built for myself yet, I cannot release as latest.  If you have time to test it out, that would help a lot.

**Comment by jamesjpenguin** [comment]
Will give it a shot this weekend and let you know!

**Comment by jamesjpenguin** [comment]
![image](https://github.com/user-attachments/assets/f73565e7-51dd-41e0-9d79-a4e5ec349e9f)

I realized when I was playing with settings (after my last commit), I had switched the last two LEDs and never updated my repo. Just opened a pull request to make that update (without the red arrow), and I recommend you update the FW to reflect that as well.

Additionally, I noticed that your FW does not set the LED option of "Turn off when suspended". Might be intentional, but I use that option and figure most people might want their controller to turn off when their computer is sleeping, up to you though.

Cheers

**Comment by mizma** [comment]
Thanks for checking! I've merged your PR on the Readme.  as for the firmware, I'll fix the mapping next weekend.

I haven't turned the "off while suspended" option on since that seems to be the default at the upstream firmware (similar to OLED off when suspended).

Thanks for the help!

**Comment by mizma** [comment]
https://github.com/mizma/GP2040-CE/releases/tag/v0.7.10-PATCH
Updated the firmware with the correct ordering.
